// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.mattermost.mattermost-grumble-plugin",
  "name": "Mattermost Grumble Plugin",
  "description": "This plugin enables voice conversation through mumble.",
  "version": "0.1.0",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "port",
        "display_name": "Mumble server port",
        "type": "number",
        "help_text": "The port that the mumble server will run in",
        "placeholder": "",
        "default": 64738
      },
      {
        "key": "cert",
        "display_name": "The TLS certificate file path",
        "type": "string",
        "help_text": "",
        "placeholder": "",
        "default": null
      },
      {
        "key": "key",
        "display_name": "The TLS key file path",
        "type": "string",
        "help_text": "",
        "placeholder": "",
        "default": null
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
